dist: bionic
services: docker
language: bash
addons:
  apt:
    packages:
      - python-pip
cache:
  directories:
    - /home/travis/docker/dataset
env:
  global:
    - PACKAGE_NAME=mcl_3dl
    - DOCKER_CACHE_TARGET=mcl3dl
    - DOCKER_CACHE_REGISTRY=atwat/ros-mcl-3dl-cache
    - DATASET_CACHE_DIR=/home/travis/docker/dataset
    - DATASET_FILE=short_test3.bag
    - DATASET_REF_FILE=short_test_ref.topic
    - secure: "Nk9LAc9NWbnf5urjmTe1nQHdzdbcKV/gYVJB2EBHiQafsn28IQ1f4BBd8tJ7+iFxnkM4I2kGtWTCvfdM91nITz0dj+MN/wbKQ0JsC1KFSi2j0ZRfnfqdQV7s3gfbGJWCQyWR3Z1RLa5FyCTNIb1Ov0fGe3/bYRiuI2mY5cKhhTuEu1grS2gFEjPiSMn3huuqGRpHYzA+a9CNfSHa9msz2AwJggsbbXhGlEz/WXZC0Irc/cLjiTtaqe82cMqxjlzmwVubZZNGHOoRmV7X7aDQmywLgySIx0eGwioz61Tz/puQ6VaZHR4eOUsuF8Jfv3HttwK56cWwQI7XraQokrMJ+fZM4qsg5v0miOeXnPSSZ3baKvAyGBcEQKRUUxiHJ8T5oYJvcRVTQWGM2WSDDlMVAG7jevyinZ9VKYEavNp5P3g7qbi6k2yX0nZ7MVYFJ9pSdowSkuh6DqCE7SnzpTYEHmgdbw5K6fPSzAoCxeKWEN2+3p/iHLT4Iw/iiEbg+FT42eXjHwhfjmNogfko8bd0phjo7R7xxM7q1pNiK4PtZpBdh/RSUgYtTNDWgDDLESgF3tTLBIH0th8b2nUFxW3NIdsY+hOrFkVuhoAd48Enepu6Ft9mA5c7iQCS0b534ah+KpTgd0D0PAQXoF9fp/qP7ri0Zr/MFSvGM4miR2HRvb8="
  matrix:
    - ROS_DISTRO_TARGET=melodic
    - ROS_DISTRO_TARGET=kinetic
branches:
  only:
    - master

before_install:
  - .travis/load_cache.sh
  - .travis/cache_dataset.sh
  - pip install --user gh-pr-comment

script:
  - docker build
    --cache-from ${DOCKER_CACHE_REGISTRY}:${ROS_DISTRO_TARGET}
    -t ${DOCKER_CACHE_TARGET}:${ROS_DISTRO_TARGET}
    -f .travis/Dockerfile
    --build-arg ROS_DISTRO=${ROS_DISTRO_TARGET}
    --pull=true ${TRAVIS_BUILD_DIR}
    || (gh-pr-comment "[[#${TRAVIS_BUILD_NUMBER}](${TRAVIS_BUILD_WEB_URL})] FAILED on ${ROS_DISTRO_TARGET}" "docker build failed"; false)
  - docker run --rm -it
    -e TRAVIS_PULL_REQUEST
    -e TRAVIS_REPO_SLUG
    -e TRAVIS_BOT_GITHUB_TOKEN
    -e GITHUB_API_URL_BASE
    -e TRAVIS_BUILD_NUMBER
    -e TRAVIS_BUILD_WEB_URL
    $(bash <(curl -s https://codecov.io/env))
    ${DOCKER_CACHE_TARGET}:${ROS_DISTRO_TARGET} /catkin_ws/src/${PACKAGE_NAME}/.travis/test.sh
  - .travis/save_cache.sh

jobs:
  include:
    - stage: test
      env:
        - ROS_DISTRO_TARGET=noetic
      script:
        - BUILD_LINK="[[#${TRAVIS_BUILD_NUMBER}](${TRAVIS_BUILD_WEB_URL})]"
        - |
          docker run -it --rm \
            -v $(pwd):/src/$(basename $(pwd)):ro \
            alpineros/ros-abuild:3.11-noetic \
            && gh-pr-comment "${BUILD_LINK} PASSED on ${ROS_DISTRO_TARGET}" \
              "Tested on Alpine ROS" \
            || (gh-pr-comment "${BUILD_LINK} FAILED on ${ROS_DISTRO_TARGET}" \
              "Tested on Alpine ROS"; false) \
    - stage: prerelease-test
      if: head_branch =~ ^release-.*$
      env:
        - ROS_DISTRO_TARGET=kinetic
      before_install: pip install --user gh-pr-comment
      script: .travis/prerelease_test.sh
    - stage: prerelease-test
      if: head_branch =~ ^release-.*$
      env:
        - ROS_DISTRO_TARGET=melodic
      before_install: pip install --user gh-pr-comment
      script: .travis/prerelease_test.sh
    - stage: prerelease-test
      if: head_branch =~ ^(release-.*|ci-for-noetic)$
      env:
        - ROS_DISTRO_TARGET=noetic
      before_install: pip install --user gh-pr-comment
      script: .travis/prerelease_test.sh
