sudo: required
services: docker

cache:
  directories:
    - /home/travis/docker/
env:
  global:
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.lz4
    - DATASET_CACHE_DIR=/home/travis/docker/dataset
    - DATASET_FILE=short_test.bag
    - DATASET_REF_FILE=short_test_ref.topic
branches:
  only:
    - master

before_install:
  - .travis.scripts/setup_docker.sh
  - .travis.scripts/load_cache.sh
  - .travis.scripts/cache_dataset.sh

install: true

script:
  - docker build -t docker-mcl3dl:latest --pull=true ${TRAVIS_BUILD_DIR} --build-arg TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG TRAVIS_BOT_GITHUB_TOKEN=$TRAVIS_BOT_GITHUB_TOKEN
  - .travis.scripts/save_cache.sh

