# This file is automatically deployed from https://github.com/at-wat/.rospkg-assets.
# Please don't directly edit; update at-wat/.rospkg-assets instead.

name: bloom-release
on:
  push:
    paths:
      - package.xml
      - '*/package.xml'
    branches:
      - master

jobs:
  bloom-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: bloom release
        id: bloom
        uses: at-wat/bloom-release-action@v0
        with:
          ros_distro: melodic noetic
          github_token_bloom: ${{ secrets.BLOOM_GITHUB_TOKEN }}
          github_user: at-wat
          git_user: Atsushi Watanabe
          git_email: atsushi.w@ieee.org
          release_repository_push_url: https://github.com/${{ github.repository }}-release.git
          tag_and_release: true
          open_pr: true
      - name: create GitHub release
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release create \
            ${{ steps.bloom.outputs.version }} \
            --title "Release ${{ steps.bloom.outputs.version }}"
