# This file is automatically deployed from https://github.com/at-wat/.rospkg-assets.
# Please don't directly edit; update at-wat/.rospkg-assets instead.

name: hide-old-bot-comments
on: pull_request

jobs:
  hide-old-bot-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Hide old bot comments
        uses: kamatama41/hide-pr-comments-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message_regex: "## \\[[0-9]*\\] (PASSED|FAILED) on "
