# This file is automatically deployed from https://github.com/at-wat/.rospkg-assets.
# Please don't directly edit; update at-wat/.rospkg-assets instead.

name: prerelease
on:
  pull_request:
    branches:
      - master

jobs:
  prerelease:
    if: ${{ startsWith(github.head_ref, 'release-') }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        env:
          - ROS_DISTRO=melodic
          - ROS_DISTRO=noetic
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install gh-pr-comment
        run: |
          curl -sL https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/install.sh | sh -s
          echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-release test
        run: |
          eval export ${{ matrix.env }}
          . .github/prerelease.conf
          .github/prerelease_test.sh ${PRERELEASE_TARGETS}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.head_ref }}
